port 26379
dir /data
requirepass ${SENTINEL_PASSWORD}
sentinel resolve-hostnames yes
sentinel announce-ip ${SENTINEL_ANNOUNCE_HOST}
sentinel monitor mymaster ${REDIS_MASTER_HOST} 6379 2
sentinel auth-pass mymaster ${REDIS_PASSWORD}
sentinel down-after-milliseconds mymaster 5000
sentinel parallel-syncs mymaster 2
sentinel failover-timeout mymaster 60000
sentinel announce-port 26379
