port 6379
dir /data
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
requirepass ${REDIS_PASSWORD}
masterauth ${REDIS_PASSWORD}
min-replicas-to-write ${REDIS_MIN_REPLICAS_TO_WRITE}
min-replicas-max-lag ${REDIS_MIN_REPLICAS_MAX_LAG}
cluster-announce-ip ${REDIS_HOST}
cluster-announce-port 6379
cluster-announce-bus-port 16379
